server:
  port: 8081
  tomcat:
    max-connections: 10000
    threads:
      max: 10000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/m4a_miaosha?characterEncoding=utf-8&rewriteBatchedStatements=true&&allowMultiQueries=true
    username: root
    password: 86739043
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 42.192.62.205
    port: 6379
    database: 0
    password: 86739043
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations: classpath:/xml/*.xml
canal:
  ip: 127.0.0.1
  port: 11111
  destination: example
  username:
  password:
